name: Setup PlatformIO Environment

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install PlatformIO
        run: |
          python -m pip install platformio

      - name: Verify PlatformIO installation
        run: |
          platformio --version